name: Scrape Live Stream Link Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install core dependencies (requests, beautifulsoup4)
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # --- UNCOMMENT THESE STEPS FOR SELENIUM ---
      - name: Install Selenium dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Set up Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      # --- END UNCOMMENT ---

      - name: Run scraping script
        run: python scrape_stream.py

      - name: Commit and push updated M3U8 file
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cctv5_huaren.m3u8
          git diff-index --quiet HEAD || git commit -m "Update live stream M3U8"
          git push
